// Modules/React/Day5-6/Parth Parekh/assignment2/src/Signup.js
import React, { Component } from "react";

// 5. Create a signup component which contains field like Name, Address,
// PanNumber and interpolate these information in the paragraph
export default class Signup extends Component {
    constructor(props) {
        super(props);
        this.state = {
            Name: "",
            Address: "",
            Phnno: "",
            showInfo: false,
        };
    }
    handleChange1 = (e) => {
        const Name = e.target.value;
        this.setState({
            Name: Name,
        });
    };
    handleChange2 = (e) => {
        const Address = e.target.value;
        this.setState({
            Address: Address,
        });
    };
    handleChange3 = (e) => {
        const Phnno = e.target.value;
        this.setState({
            Phnno: Phnno,
        });
    };
    handleSubmit = (e) => {
        if (
            this.state.Name === "" &&
            this.state.Address === "" &&
            this.state.Phnno === ""
        ) {
        } else {
            this.setState({ showInfo: true });
        }
    };

    render() {
        return (
            <div className="card bg-dark  text-white mt-1">
                <h3 className="text-center">Signup Form</h3>
                <div className="form-group ">
                    <label className="h5 p-1"> Name : </label>
                    <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Name"
                        onChange={this.handleChange1}
                        aria-describedby="helpId"
                    />
                </div>
                <div class="form-group">
                    <label className="h5 p-1">Address : </label>
                    <textarea
                        class="form-control"
                        rows="3"
                        onChange={this.handleChange2}
                    ></textarea>
                </div>
                <div className="form-group">
                    <label className="h5 p-1"> Phone Number : </label>
                    <input
                        type="text"
                        className="form-control"
                        onChange={this.handleChange3}
                        aria-describedby="helpId"
                    />
                </div>
                <button
                    className="mt-3 mb-3 btn btn-outline-success "
                    onClick={this.handleSubmit}
                >
                    SignUp
                </button>
                {this.state.showInfo && (
                    <div>
                        <p className="h3 text-success m-2">
                            Name : {this.state.Name}
                        </p>
                        <p className="h3 text-success m-2">
                            Address : {this.state.Address}
                        </p>
                        <p className="h3 text-success m-2">
                            Phone Number : {this.state.Phnno}
                        </p>
                    </div>
                )}
            </div>
        );
    }
}

// Modules/Angular/Day6-7/Niraj-Sapra/Assingment/Area/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  Name:string="niraj sapra";
  Address:string="Bhavnagar";
  PanNumber:number=124568;
  Photograph:string='Niraj.png';
  Signup:string='Signup';
  constructor() { }
 
  ngOnInit(): void {
  }
  Signupuser(){
    return ("Finally Data is "+this.Name+" city is "+this.Address+" finally pannumber is "+this.PanNumber+" finally photograph is "+this.Photograph);
  }
}

<div class="md-9">
    <p class="h2 ">signup works!</p>
    <div>
        <h3>5. Create a signup component which contains field like Name,
         Address, PanNumber and interpolate these information in the paragraph
        </h3>
    </div>
    <div>Enter Name : </div>
    <div>
        <input [(ngModel)] = "Name" type="text">
    </div>
    <div>Enter Address : </div>
    <div>
        <input [(ngModel)] = "Address" type="text">
    </div>
    <div>Enter PanNumber : </div>
    <div>
        <input [(ngModel)] = "PanNumber" type="number">
    </div>
    <div>Choose photograph : </div>
    <div>
        <input [(ngModel)] = "Photograph" type="file">
    </div>
     <div>Get Signup User : </div>
     <div>
        <input class="btn btn-outline-info mt-4"  type="button" [value] = "Signup" (click) = "Signupuser()">
    </div>
    <div class="alert alert-success mt-4" role="alert">
        {{Signupuser()}}
    </div>
</div>
