// Modules/Angular/Day6-7/Bhargav Prajapati/Assignment/Assignment/src/app/circle/circle.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-circle',
  templateUrl: './circle.component.html',
  styleUrls: ['./circle.component.css']
})
export class CircleComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  Radius: number = 0
  Pi: number = 3.14
  result: number = 0;

  Calculate(): void {
    this.result = this.Pi * this.Radius * this.Radius
  }
}

<div class="card">
    <div class="card-header text-center">
        <p class="text-muted" style="font-size: 35px;">Area of Circle </p>
    </div>
    <div class="card-body">
        <div class="form-group">
            <label for="">Enter The Radius :-</label>
            <input type="number" class="form-control" [(ngModel)]="Radius">
            <button class="btn btn-primary mt-3" (click)="Calculate()">Calculate</button>
        </div>
        <pre class="text-success" style="font-size: 20px;">

            Area of Circle=Pi*r*r
                          ={{Pi}}*{{Radius}}*{{Radius}}
                          ={{result}}


                             
                     </pre>
    </div>
</div>

// Modules/React/Day5-6/Vatsal Parmar/additional-assignment/src/components/Circle.js
import React from "react";

class Circle extends React.Component {
  constructor(props) {
    super(props);
    this.state = { radius: 0 };
  }
  handleChange = (e) => {
    this.setState({ radius: e.target.value });
  };
  render() {
    return (
      <div className="border border-primary p-3 rounded" id="circle">
        <h2 className="text-primary text-center">Find The Area Of Circle</h2>
        <div className="form-group">
          <p className="text-primary my-2">
            <b>Enter Radius : </b>
          </p>
          <input
            className="form-control w-50 text-primary"
            id="radious"
            onChange={this.handleChange}
            placeholder="Radius"
            type="number"
          />
        </div>
        <p className="text-primary my-2">
          <b>Area Of Circle : </b>
          {3.14 * this.state.radius * this.state.radius}
        </p>
      </div>
    );
  }
}

export default Circle;
