// Modules/Angular/Day6-7/Niraj-Sapra/Assingment/Area/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  uname:string="admin";
  lpassword:string="admin";
  Login:string="Login";
  constructor() { }

  ngOnInit(): void {
  }
  Loginuser(){
    if(this.uname == 'admin' && this.lpassword == "admin"){
      alert("Login Successfully");
    }
    else
    {
      alert("User-Name and Password is not Right.");
    }
  }
}

     <p>login works!</p>

    <div class="h4" > Create Login Component which validate a user with below credential username=admin, password=admin 
    </div>
    <div>Enter User Name : </div>
    <div>
        <input [(ngModel)] = "uname" type="text">
    </div>
    <div>Enter password : </div>
    <div>
        <input [(ngModel)] = "lpassword" type="text">
    </div>
     <div>Get Login User : </div>
     <div>
        <input  type="button" [value] = "Login" (click) = "Loginuser()">
    </div>

// Modules/React/Day5-6/Parth Parekh/assignment2/src/Login.js
import React, { Component } from "react";

// 2. Create Login Component which validate a user with below credential username=admin, password=admin
export default class Login extends Component {
    constructor(props) {
        super(props);
        this.state = {
            username: "",
            password: "",
            message: "",
        };
    }
    handleChange1 = (e) => {
        const username = e.target.value;
        this.setState({
            username: username,
        });
    };
    handleChange2 = (e) => {
        const password = e.target.value;
        this.setState({
            password: password,
        });
    };
    handleSubmit = (e) => {
        const username = this.state.username;
        const password = this.state.password;

        if (username === "admin" && password === "admin") {
            this.setState({
                message: "Admin Login Successfully Done",
            });
        } else {
            this.setState({ message: "Incorrect Username and Password" });
        }
    };

    render() {
        return (
            <div className="card bg-dark text-white">
                <h3 className="text-center p-1">Login Form</h3>
                <div className="form-group ">
                    <label className="h5 p-1">Username : </label>
                    <input
                        type="text"
                        className="form-control "
                        placeholder="Enter Username"
                        onChange={this.handleChange1}
                        aria-describedby="helpId"
                    />
                </div>
                <div className="form-group">
                    <label className="h5 p-1">Password : </label>
                    <input
                        type="password"
                        className="form-control"
                        placeholder="Enter Password"
                        onChange={this.handleChange2}
                        aria-describedby="helpId"
                    />
                </div>
                <button
                    className="mt-3 btn btn-outline-primary"
                    onClick={this.handleSubmit}
                >
                    Login
                </button>
                <p className="h3 text-success m-2">{this.state.message}</p>
            </div>
        );
    }
}
